<?php
namespace FreePBX\modules\Frogman\Dialplan;

/**
 * Base class for dialplan templates.
 */
abstract class TemplateBase {

	/**
	 * Template identifier.
	 */
	abstract public function id();

	/**
	 * Human-readable name.
	 */
	abstract public function name();

	/**
	 * Description of what this template builds.
	 */
	abstract public function description();

	/**
	 * Example natural language that triggers this template.
	 */
	abstract public function examples();

	/**
	 * Generate the dialplan context block.
	 * Returns the full text to append to extensions_custom.conf.
	 */
	abstract public function generate($params);

	/**
	 * Generate a context name from params.
	 */
	protected function contextName($prefix, $params) {
		$id = $params['extension'] ?? $params['name'] ?? $params['did'] ?? 'custom';
		$clean = preg_replace('/[^a-zA-Z0-9]/', '-', strtolower($id));
		return "oc-{$prefix}-{$clean}";
	}

	/**
	 * Build a priority-numbered extension block.
	 * Takes an array of app calls, returns numbered exten lines.
	 */
	protected function buildExten($exten, $apps) {
		$lines = [];
		foreach ($apps as $i => $app) {
			$pri = ($i === 0) ? '1' : 'n';
			$lines[] = "exten => {$exten},{$pri},{$app}";
		}
		return $lines;
	}

	/**
	 * Header comment for generated contexts.
	 */
	protected function header($description) {
		$timestamp = date('Y-m-d H:i:s');
		return "; Generated by Frogman on {$timestamp}\n; {$description}";
	}
}
